[package]
name = "lineage-finance"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.29"
anchor-spl = "0.29"
solana-program = "1.17"
pyth-sdk-solana = "0.8"
spl-token = "4"

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
